name: workflow-run
on: 
    workflow_run: 
        workflows: [push-pullreq-issues-activitytype] 
        types: [completed]
        # This workflow-run workflow will run after compltion of push-pullreq-issues-activitytype.
jobs:
    demo-script:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello World"