name: manual-checkout
on:
    push:
    workflow_dispatch: 
jobs:
  Manual-Clone:
    runs-on: ubuntu-latest
    steps:
      - name: Before checkout
        run: ls -a
      - name: Checkingout
        run: git clone https://$MY_GITHUB_USERNAME:${{secrets.MY_GITHUB_TOKEN}}@github.com/parassankhyadhar/upskilling.git
      - name: After cloning
        run: |
          cd upskilling
          ls -a
  Using-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Before checkout
        run: ls -a
      - name: Ceckout Action
        uses: actions/checkout@v4
      - name: After cloning
        run: ls -a
          