name: first-workflow
on: [push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      -  name: Echo Hello World
         run: echo "Hello World"
      -  name: Multiline Command
         run: |
              echo "Hi"
              echo "Paras"
