name: first-workflow
on:
  push:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      -  name: Echo Hello World
         run: echo "Hello World"
      -  name: Multiline Command
         run: |
              echo "Hi"
              echo "Paras"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo from second job
        run: echo "Hello second job."
  third-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Echo from thired job
        run: echo "Hello Third job"